sudo: false

language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot
env:
  - GROUP=default

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

stages:
  - analyze
  - test

jobs:
  exclude:
    - php: 7.3
  include:
    - stage: analyze
      php: 7.3
      install:
        - pecl install ast
        - phpenv config-rm xdebug.ini
        - composer install --prefer-dist
      script:
        - make ci-analyze --keep-going
        - composer validate

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev
      phan/phan phpstan/phpstan vimeo/psalm
      infection/infection friendsofphp/php-cs-fixer
  - composer install --prefer-dist

script:
  - make ci-test --keep-going PHPUNIT_GROUP=$GROUP

after_success:
  - travis_retry php vendor/bin/php-coveralls
